### ISSUE TITLE
Find Time Data

### ISSUE THREAD

**Issue by maerci** [Rufman91/ForceMapAnalysis#23]
Is there a way to find the time data next to force and height data? Or: Where can I find the time data in the unzipped folders?

**Comment by Rufman91** [comment]
This is an issue that Orestis has noticed a while ago: JPK does not seem to actually save the timedata to the files. You may need to convert Height data to time-data by dividing through the cantilever-tip-velocity for linear segments (approach, retract) and somehow calculate it for the sinusoidal parts from the frequency.
I'd suggest, you contact Orestis about it first, because we might need to ask for a solution from JPKs side.

**Comment by maerci** [comment]
Ok, thank you for the idea! I will write an E-Mail to Orestis. And maybe I will first try to divide the time span (which I get in the header properties) through the number of data points..

**Comment by Rufman91** [comment]
Ah, of course, good idea! That should give you the time between two data points, assuming that the afm samples its data at a constant rate. You can check that by comparing the frequency in the file header to the one you get by plotting your 'time-converted' data.

**Comment by maerci** [comment]
I created a time vector by dividing the time span of each segment by the number of points in each segment - I compared this vector to the time series data I got from extracting the data as a .txt file and they are equivalent! :)

**Comment by Rufman91** [comment]
Amazing work. Thats the spirit ;D
