### ISSUE TITLE
Warning Cantilever Images

### ISSUE THREAD

**Issue by maerci** [Rufman91/ForceMapAnalysis#30]
![warning_cantileverimages_20210412](https://user-images.githubusercontent.com/79519194/114437805-4d250100-9bc7-11eb-90af-480212f3c9bf.JPG)
It's me again: Now that I have the Experiment, I want to try out a general analysis but getting this warning signal and I don't know how to act..

**Comment by Rufman91** [comment]
Do you have a calibration-image of your cantilever? The one where you image a cone on a silicon chip to get the tip-shape.

Otherwise Oliver-Pharrian analysis wont work. 
Hertzian analysis will work, though, if you're just testing the analysisprocess
(Additonally: does your data have the snap-in effect in the approach part? If not, 'Old' is a better choice for contact point estimation)

**Comment by maerci** [comment]
Where do I get this image? During the calibration process? & more important: Can I get it now after experiments are done? Or do I have to repeat them (the calibration)?

Thank you also for the information about the 'Snap-In', I suspected already that this may not be the right way to calculate the contact point in this case..

**Comment by Rufman91** [comment]
There are so-called 'calibration gratings' (in our case TGT-1, if you want to look it up) that can be used to figure out the exact tip shape. You need to take a contact-mode or AC-mode image of such a grating. If you still have the cantilever with which you did your measurements, you can still image it after your experiments; thats no big issue.
You should ask Orestis, if thats really necessary, though.

It should also be noted that Oliver-Pharrian analysis is in principle also possible for an 'ideal' cantilever tip shape, calculated from the manufacturers nominal values for tip geometry. This method is very inaccurate, though, which is why i never prioritised implementing it in the software. I'll do so in a (distant) future update, though.

Cheers

**Comment by maerci** [comment]
![error_unrecognizedproperty_20210413](https://user-images.githubusercontent.com/79519194/114545085-cff79b80-9c5b-11eb-9bd2-6c423d8c8d17.JPG)

Thank you! I tried it today with Orestis in the lab and he also sent me a tgt1-image, that I can load in the script, but now I get this error?
At the end I want to perform a Oliver-Pharr-Analysis, but maybe I will just try to write the code "blind", so without trying, and then just inform you, so that maybe we can have a look together.
Thank you again for answering my questions so quickly! :)

**Comment by Rufman91** [comment]
Hey, no worries., i think its time to merge all the recent changes over to your branch. I think that would get rid of these error messages.
Can you commit all your local changes to your brach and inform me as soon as you have done that, so i can do a merge from master?

After that its a good idea to load in your files.

If you want, we can hop onto zoom right now adn go through this together. If you don't have time, just inform me about your commit, as soon as you've pushed them.

**Comment by maerci** [comment]
I have no local changes at the moment, I already pushed all what I have done. So you can merge your changes!
Before meeting on zoom I would like to finish as good as possible my programming part, which should be done this evening hopefully. I will let you know!

**Comment by Rufman91** [comment]
Alright. Did the merge. Everything should work properly now, if you load your data into a new Experiment.
