### ISSUE TITLE
Fibril aspect ratio 

### ISSUE THREAD

**Issue by fuchsm6011** [Rufman91/ForceMapAnalysis#35]
Having an estimate for fibril width after fibril segmentation would be awesome! :)

**Comment by Rufman91** [comment]
There already is an implementation for fibril witdh: the AFMBaseClass method characterize_fiber_like_polyline_segments() determines among other things the FWHM of polyline segments.
In order to have a proper estrimate of true fibril diameter, the fibril cross-sectional area has to be determined.

Commit: 0d91b170d471340bfa08736f211ba1bb306016e1

Expanded characterize_fiber_like_polyline_segments() to also output area and a bunch of other derived characteristics, such as AreaDerivedDiameter, WidthBase, explizit AspectRatios and many medians and means.
Beware that characterize_fiber_like_polyline_segments() has 3 outputs. The first is good for plotting, the other two provide more information aswell as means and medians.

![image](https://user-images.githubusercontent.com/63786485/153890279-e67e767f-5528-4eab-a338-068d88bff001.png)

characterize_fiber_like_polyline_segments() has many NameValue inputs. You can read about their purposes in the function header though the defaults already give pretty good values. For further reading, a lot of whats happening in characterize_fiber_like_polyline_segments() builds on MATLABs built-in findpeaks().
